### ISSUE TITLE
选择器中没有12月份的选择，只有1-11月份选择

### ISSUE THREAD

**Issue by 2556588** [limintao/react-native-date-picker#2]
DateTimePicker
            mode="wheel"
            timePicker={true}
            date={dayjs()}
            columns={["year", "month", "day", "hour", "minute"]}
            format="YYYY-MM-DD HH:mm"
            containerStyle={{
              width: 400,
            }}
            height={300}
            displayFullDays={true}
            wheelPickerTextStyle={{
              fontSize: 16
            }}
          />为啥没有12月份的选择，当前时间"2024-11-14"

**Comment by limintao** [comment]
已在0.0.6版本中解决！
